### ISSUE TITLE
License concerns

### ISSUE THREAD

**Issue by hyandell** [stg-tud/MUDetect#15]
Looking at the license this software doesn't appear to be being made available for general use, which seems out of sync with the README which is encouraging readers to use the software. Looking at the license, which seems to spend too much time trying to be funny, it only appears to allow use of the software to validate claims in a published paper.

Can I offer a belated +1 to #1 's Apache option?

**Comment by salsolatragus** [comment]
Thanks for raising this concern and sorry for taking so long to respond. CRAPL actually allows validation of published papers and new scientific work. Nevertheless, I just changed to license to MPL 2.0, in order to allow non-scientific use of the code as well.
